-- Run this in the Supabase SQL Editor

-- Create Categories Table
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
    icon TEXT
);

-- Create Transactions Table
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC NOT NULL,
    date DATE NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
    description TEXT,
    user_id BIGINT,
    category_id BIGINT REFERENCES categories(id)
);

-- Insert Default Categories
INSERT INTO categories (name, type, icon) VALUES 
('Salary', 'income', 'monetization_on'),
('Freelance', 'income', 'computer'),
('Groceries', 'expense', 'shopping_cart'),
('Netflix', 'expense', 'video_library'),
('Starbucks', 'expense', 'coffee');

-- (Optional) Insert some dummy data so the app isn't empty right away
INSERT INTO transactions (amount, date, type, description, user_id, category_id) VALUES
(850.00, CURRENT_DATE, 'income', 'Upwork', 1, 2),
(15.00, CURRENT_DATE - INTERVAL '1 day', 'expense', 'Starbucks', 1, 5),
(12.00, CURRENT_DATE - INTERVAL '3 days', 'expense', 'Netflix', 1, 4);
